<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // 第一步 promise的声明 是一个类
    // 第二步 解决基本的状态
    // 第三步 定义then方法
    // 第四步 解决settimeout异步实现问题
    // 第五步 链式调用（难点）
    // 第六步 解决其他问题
    // 1.Promise A+规范中 规定：onFulfilled,onRejected都是可选参数，如果他们不是函数，必须被忽略
    // 2.而且规定：onFulfilled，onRejected都必须是异步执行
    // 3.如果onFulfilled或onRejected报错，则直接返回reject()
    // 第七步 添加 catch、resolve、reject、all和race方法
    // 手写all方法是重点

    class diyPromise  {
      static PENDING = 'pending'
      static FULFILLED = 'fulfilled'
      static REJECTED = 'rejected'
      constructor(executor) {
        // 初始化状态
        this.status = diyPromise.PENDING
        // 成功的值
        this.value = undefined
        // 失败的原因
        this.reason = undefined
        // 成功的队列
        this.onFulfilledCallbacks = []
        // 失败的队列
        this.onRejectedCallbacks = []
        // 成功
        let resolve = (value) => {
          // 添加条件判断的原因是 当status的状态被改变过以后 调用resolve就会失败
          if (this.status === diyPromise.PENDING) {
            this.status = diyPromise.FULFILLED
            // 储存成功的值
            this.value = value
            // 一旦resolve执行 调用成功数组中的函数
            this.onFulfilledCallbacks.forEach(cb => cb())
          }
        }
        // 失败
        let reject = (reason) => {
          if (this.status === diyPromise.PENDING) {
            this.status = diyPromise.REJECTED
            // 储存失败的原因
            this.reason = reason
            // 执行reject 的时候 调用失败数组中的函数
            this.onRejectedCallbacks.forEach(cb => cb())
          }
        }
        // 如果executor执行出错 直接捕获
        // 通过executor执行器 立即执行
        try {
          executor(resolve, reject)
        }catch(e) {
          reject(e)
        }
      }
      // 添加catch方法
      catch(fn) {
        return this.then(null, fn)
      }
      // 添加回调方法then
      then(onFulfilled, onRejected) {
        // promise规范中规定onFulfilled如果不是函数 返回的就是一个value
        // onRejected同理
        onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value
        onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err }
        // 需要声明返回一个新的promise对象
        let newPromise = new diyPromise((resolve, reject) => {
          // 成功的回调
          if (this.status === diyPromise.FULFILLED) {
            // 传入成功的值
            setTimeout(() => {
              try {
                const x = onFulfilled(this.value)
                // resolvePromise函数，处理自己return的promise和默认的promise2的关系
                resolvePromise(newPromise, x, resolve, reject)
              } catch (error) {
                reject(error)
              }
            })
          }
          // 失败的回调
          if (this.status === diyPromise.REJECTED) {
            setTimeout(() => {
              try {
                const x = onRejected(this.reason)
                resolvePromise(newPromise, x, resolve, reject)
              } catch (error) {
                reject(error)
              }
            })
          }
          // 如果当前状态没变化的时候
          if (this.status === diyPromise.PENDING) {
            // 成功方法传入到成功数组中
            this.onFulfilledCallbacks.push(() => {
              setTimeout(() => {
                try {
                  const x = onFulfilled(this.value)
                  resolvePromise(newPromise, x, resolve, reject)
                } catch (error) {
                  reject(error)
                }
              })
            })
            // 失败方法传到失败数组中
            this.onRejectedCallbacks.push(() => {
              setTimeout(() => {
                try {
                  const x = onRejected(this.reason)
                  resolvePromise(newPromise, x, resolve, reject)
                } catch (error) {
                  reject(error)
                }
              })
            })
          }
        })
        // 返回新的promise
        return newPromise
      }
    }

    // 封装判断promise方法
    function resolvePromise(newPromise, x, resolve, reject) {
      // 循环引用则报错
      if (newPromise === x) {
        reject(new TypeError('禁止循环调用'))
      }
      // 防止多次调用
      let called
      // 如果不为null且为函数或者对象
      if (x !== null && (typeof x === 'object' || typeof x === 'function')) {
        try{
          let then = x.then
          // 如果x的then方法是一个函数 就默认是promise
          if (typeof then === 'function') {
            // 就让then往下执行
            then.call(
              x, 
              // 成功的方法
              res => {
                // 成功和失败只能调用一次
                if (called) return //调用过则退出
                // 第一次调用
                called = true
                resolvePromise(newPromise, res, resolve, reject)
              }, 
              // 失败的方法
              err => {
                if (called) return 
                called = true
                // 失败了就失败了
                reject(err)
              })
          }
        }catch(e) {
          // 也属于失败
          if (called) return
          called = true
          // 取then出错了那就不要在继续执行了
          reject(e)
        }
      }else {
        resolve(x)
      }
    }
    // 添加resolve方法
    diyPromise.resolve = function (value) {
      return new diyPromise((resolve, reject) => {
        resolve(value)
      })
    }
    // 添加reject方法
    diyPromise.reject = function (reason) {
      return new diyPromise((resolve, reject) => {
        reject(reason)
      })
    }
    // 添加race方法
    diyPromise.race = function (promises) {
      return new diyPromise((resolve, reject) => {
        for(let i = 0; i < promises.length; i++) {
          return promises[i].then(resolve, reject)
        }
      })
    }
    // 添加promise.all方法
    // 重点
    // 1.传进来的promise是什么顺序 传出去就是什么顺序
    // 2.传进来的参数可能不是promise对象 没有then方法 promise.resolve() 方法会将所有传进来的值包装成一个promise对象
    // 3.如果中间发生错误应该直接返回错误 不往下继续执行
    diyPromise.all = function (promises) {
      // 最后需要返回的结果数组
      let result = []
      // 传进来的promise数组长度
      let length = promises.length
      // 判断执行的次数
      let count = 0
      return new diyPromise((resolve, reject) => {
        for(let i = 0; i < length; i++) {
          diyPromise.resolve(promises[i]).then(res => {
            result[i] = res
            count++
            if (count === length) {
              resolve(result)
            }
          }).catch(e => {
            reject(e)
          })
        }
      })
    }

    // const p1 = new diyPromise((resolve, reject) => {
    //   resolve(1)
    // })
    // p1.then(res => {
    //   console.log(res)
    // })
    // p1.then(res => {
    //   console.log(2)
    // }).resolve(e => {
    //   console.log(e)
    // })

    // 测试promise.all
    const p1 = new Promise((resolve, reject) => {
      resolve(1)
    })
    const p2 = new Promise((resolve, reject) => {
      resolve(2)
    })
    const p3 = new Promise((resolve, reject) => {
      resolve(3)
    })
    const p = Promise.all([p1, p2, p3, 4])
    p.then(res => {
      console.log(res)
    })
    promiseAll([p1, p2, p3, 4]).then(res => {
      console.log(res)
    })
    // console.log(Object.prototype.toString.call(function() {}));
    // 手写promise.all
    // 1.传进去的就是一个promise数组
    // 2.返回的就是一个promise对象
    // 3.数组中 传进来的不一定都是promise对象 有可能是某个值 则需要用promise.resolve包装 不管是什么值都会返回promise
    // 4.返回的顺序和传入的顺序一样

    function promiseAll(promises) {// 最后需要返回的结果数组
      let result = []
      // 传进来的promise数组长度
      let length = promises.length
      // 判断执行的次数
      let count = 0
      return new Promise((resolve, reject) => {
        for(let i = 0; i < length; i++) {
          Promise.resolve(promises[i]).then(res => {
            result[i] = res
            count++
            if (count === length) {
              resolve(result)
            }
          }).catch(e => {
            reject(e)
          })
        }
      })
    }
    // const pp = promiseAll([p1, p2, p3])
    // pp.then(res => {
    //   console.log(res);
    // })
  </script>
</body>
</html>